### ISSUE TITLE
请问兼容性如何？

### ISSUE THREAD

**Issue by az031120103** [lirl-cn/vue2.7-vite-common#1]
ie 9及以上浏览器都支持吗

**Comment by lirl-cn** [comment]
抱歉，并没有对IE进行兼容处理。

**Comment by lirl-cn** [comment]
> ie 9及以上浏览器都支持吗

抱歉，因为我们的项目无需兼容IE及低版本浏览器，所以并没有对IE进行兼顾处理。如果可以的话，你可以把项目clone下来，自己改造一下
